### ISSUE TITLE
Line break

### ISSUE THREAD

**Issue by prachi708** [noemilosada/naoTooltips#1]
how to add line break in text of tooltip. If text is given using variable in javascript

**Comment by noemilosada** [comment]
You can add `\n` or `\r` to your text. https://en.wikipedia.org/wiki/Newline#Representations
`var text = "Hello this \n is a new line"`
`var text = "Hello this \r is a new line"`

This is not an actual issue with the plugin so I'll close it.

**Comment by prachi708** [comment]
its doesn't solve my issue
It is solved by using <p> in my text.
